const getTopics = (num) => {
    let topics = ["🐞 Nature", "🍥 Anime", "🍿 Entertainment", "🎮 Games", "🌭 Food", "📕 General", "🎵 Music", "🏀 Sports", "💻 Technology", "🐲 Pokemon"]
    return [...topics].sort(() => 0.5 - Math.random()).slice(0,num)
}

const getWordsFromTopic = (topic) => {
    const categories = {
        "Nature": ["mammal", "freshwater fish", "omnivore", "hervivore", "organism", "wildlife", "creature", "embryo", "critter", "human nature", "predator", "squid", "oxygen", "reproduction", "bacteria", "sponge", "scavenger", "oyster", "octopus", "rhinosoraus", "dinosaur", "reptile", "energy", "centipede", "orangutan", "reptile", "chicken", "microorganism", "wild animal", "creepy crawler", "cold blooded", "warm blooded", "cell membrane", "food chain", "hibernation", "sea lion", "sea urchin", "human society", "polar bear", "arctic", "beach", "coast", "countryside", "desert", "environment", "field", "forest", "island", "meadow", "mountain"],
        "Anime": ["narto shippuden", "talk no jutsu", "shadow clone jutsu", "sexy jutsu", "akatsuki", "anbu", "bingo book", "byakugan", "chakra", "chidori", "chunin exam", "eight gates", "fillers", "genjutsu", "hand signs", "hokage", "kamui", "kunai", "ichiraku ramen", "madara", "rock lee", "sakura", "sasuke", "shuriken", "sharingan", "susanoo", "one piece", "monkey d luffy", "zoro", "sanji", "nico robbin", "god usopp", "cyborg franky", "brook", "devil fruit", "observation haki", "straw hat", "the one piece is real", "two piece", "fourth sword style", "true triple katana", "ace", "pirate king", "grand line", "alabasta", "marineford", "skypiean", "fishman", "cybrog", "mink", "joy boy", "yugioh", "blue eyes white dragon", "dark magician girl", "dark magician", "exodia", "bleach", "dragon ball", "super saiyan", "goku black", "spirt bomb", "kamehameha", "kaioken", "krillin", "ultra instinct", "ulta ego", "frieza", "jujutsu kaisen", "demon slayer", "fire breathing", "water breathing", "sun breathing", "akaza", "bankai", "hollow", "sosuke aizen", "boruto next generations", "domain expansion", "cursed spirit", "sage mode", "baryon mode", "plot armor", "a thousand years of death", "senpai", "baka", "sugoi", "my hero academio", "one for all", "all for one", "all might", "half hot half cold", "overhaul", "plus ultra", "nomu", "bakugo", "deku", "hunter hunter", "spy x family", "one punch man", "no game no life", "death note", "shinigami", "ill take a potato chip and eat it", "attack on titan", "founder titan", "colossal titan", "armored titan", "beast titan"],
        "Entertainment": ["everything everywhere all at once", "nope", "avatar the last airbender", "scooby doo", "fire bender", "earth bender", "water bender", "air bender", "king kong", "planet of the apes", "the ten commandments", "your name", "spirited away", "independence day", "i am legend", "star wars", "the force", "lightsaber", "iron man", "harry potter", "avengers endgame", "titanic", "jurassic world", "frozen", "shrek", "toy story", "the lion king", "dispicable me", "jumanji", "black panther", "the hunger games", "superman", "pirates of the caribbean", "batman", "bat mobile", "the joker", "the hulk", "harley quinn", "finding nemo", "cinderella", "aladdin", "guardians of the galaxy", "deadpool", "beauty and the beast", "suicide squad", "transformers", "alice in wonderland", "pinocchio", "ghostbusters", "spider man"],
        "Games": ["yessir", "gottem", "be right back", "good game", "skill issue", "on 5  b
        0\my way", "good luck have fun", "get rekt", "away from keyboard", "easter egg", "frames per second", "pvp", "npc", "bot", "l bozo", "rip bozo", "for the win", "grand theft auto", "valorant", "fortnite", "pokemon go", "fall guys", "nintendo", "gamestop", "playstation", "genshin impact", "roblox", "deathmatch", "god mode", "moba", "role playing game", "simulator", "lag", "sea of theives", "assassins creed", "super mario", "resident evil", "half life", "the legend of zelda", "red dead redemption", "halo", "breath of the wild", "ocarina of time", "final fantasy", "super smash bros", "tetris", "dark souls", "deepwoken", "blox fruits", "shindo life", "bloodbrone", "fallout", "league of legends", "borderlands", "mega man", "animal crossing", "mortal kombat", "knockout city", "donkey kong", "call of duty", "team fortress two", "overwatch", "apex legends", "pan man", "sonic", "world of warcraft", "metroid", "pokemon go", "metal gear rising", "minecraft", "portal", "street fighter", "undertale", "counterstrike global offensive", "the sims", "cooking mama", "papas pizzaria", "run", "fire boy and water girl", "super smash flash", "balloon tower defence", "geometry dash", "temple run", "subway surfers", "angry birds", "candy crush", "flappy bird", "agario", "slitherio", "guitar hero", "cookie clicker", "among us", "osu", "multiverses", "rocket league", "for honor", "titanfall", "cyberpunk", "cut the rope", "kirby"],
"Food": ["spaghetti", "noodles", "cup noodles", "cheese", "doritos", "mountain dew", "cheez its", "milk chocolate", "dark chocolate", "peanut butter", "chicken over rice", "lamb over rice", "pepperoni pizza", "macaroni and cheese", "cheese pizza", "chicken soup", "boba", "steak", "salmon", "beef", "pork", "oyster", "tilapia", "onion", "onion fries", "mashed potato", "home fries", "pancake", "waffle", "frech toast", "crepe", "grapes", "srammbled eggs", "kabab", "lamb chop", "fried chicken", "taco", "burrito", "empanada", "dumpling", "donut", "bagel", "dino nuggets", "pho", "brownie", "cookies", "fish sticks", "briyani", "vindaloo", "daal", "aloo bhaji", "green tea", "pakora", "chai", "paimon","chanachur"],
        "General": ["happy birthday", "happy new year", "happy thanksgiving", "peter piper picked a peck of pickled peppers", "its raining cats and dogs", "kill two birds with one stone", "live and learn", "better late than never", "beat around the bush", "bite the bullet", "break a leg", "call it a day", "cut me some slack", "easy does it", "out of hand", "get your act together", "hang in there", "rocket science", "sharko", "hero blade", "long story short", "no pain no gain", "on the ball", "pull yourself together", "so far so good", "speak of the devil", "best of both worlds", "under the weather", "you can say that again", "a picture is worth a thousand worlds", "add insult to injury", "break the ice", "apples and oranges", "an arm and a leg", "the drop of a hat", "cold shoulder", "wild goose chase", "bigger fish", "nail on the road", "ignorance is bliss", "piece of cake", "look before your jump", "once in a blue moon", "thin ice", "spill the beans", "drip check", "vibe check", "wave check", "nine lives", "snowball effect", "butterfly effect", "an apple a day keeps the doctor away", "calm before the storm", "curiosity killed the cat", "go down in flames", "head in the clouds", "jump on the bandwagon", "the ship has sailed", "time is money", "eye to eye", "get your money up", "get your funny up", "hit the sack", "stab in the back", "lose your touch", "sit tight", "pitch in", "ring a bell", "blow off steam", "cut to the chase", "up in the air", "get over it", "everything everywhere all at once", "rags to riches", "sticky fingers", "break even", "break the bank", "locked and loaded", "make ends meet", "rule of thumb", "keep your chin up", "spice things up", "cool as a cucumber", "couch potato", "in hot water", "cup of tea", "can i get a bottle of water", "butter up", "food for thought", "smart cookie", "bad apple", "bread and butter", "peanut butter and jelly", "when life gives you lemons", "hard nut to crack", "sweet tooth", "brewing storm", "rain or shine", "under the sun", "deep water", "go with the flow", "lost at sea", "gain ground", "walking on air", "castle in the sky", "down to earth", "tip of the iceburg", "clear as mud", "cold as stone", "beef up", "monkey business", "monke time", "hold your horses", "cheap shot", "game plan", "call the shots", "get a kick out of it", "make the cut", "take sides", "toe to toe", "bare bones", "get it off your chest", "belly up", "play it by ear", "slap on the wrist", "bang for your buck", "going forward", "moving forward", "hold the line", "pass the buck", "reach out", "top of the line", "touch base", "touch grass", "up my alley", "wet blanket", "one trick pony", "cloud nine", "gold digger", "teachers pet", "two peas in a pod", "party pooper", "left in the dark", "going in circles", "elephant in the room", "full swing", "safe bet", "full throttle", "taste of your own medicine", "kill time", "time flies", "third times the charm", "bigger fish to fry", "through think and thin", "keep calm"],
        "Music": ["juice wrld", "meoldic rap", "singing", "rock and roll", "the weekend", "drake", "lil nas x", "bts", "eminem", "taylor swift", "charlie puth","lean wit me", "blueberry faygo", "ransom", "hurt me", "lo mein", "maze", "sanguine paradise", "empty", "all girls are the same", "xo tour", "nowadays", "shotta flow", "bleed it", "godzilla", "whats popping", "bad boy", "the box", "moonlight", "bruno mars", "ed sheeran", "twice", "tame impala","lil baby", "blue face", "lil Uzi", "lil peep", "xxxtentacion", "bad bunny", "black pink", "beat it", "shape of you", "who let the dogs out", "old town road", "lucid dreams", "all my friends are dead", "push me to the edge", "bad romance", "billie jean", "i will survive", "once i was eleven years old", "stairway to haven", "despacito", "dame tu cosita", "smooth criminal", "lean on me", "somebody i used to know", "let it go", "all i want for christmas is you", "its beginning to look a lot like christmas", "gods plan", "justin bieber", "the world is gonna roll me", "i aint the sharpest tool in the shed", "hello darkness my old friend", "my life got flipped turned upside down", "i wanna be the very best", "im sexy and i know it", "hit or miss", "hello its me", "the haters gonna hate", "my anxiety the size of a planet", "my milkshake brings all the boys to the yard", "mans not hot"],
        "Sports": ["soccer", "football", "cricket", "handball", "baseball", "archery", "athletics", "badminton", "basketball", "diving", "fencing", "judo", "gymnastics", "swimming", "table tennis", "taekwondo", "tennis", "volleyball", "skateboard", "roller blade", "ice skate", "ice hockey", "snowboard", "cross country", "boxing", "beach volleyball", "cycling", "golf", "karate", "powerlifiting", "rowing", "sailing", "shooting", "sking", "climbing", "wrestling", "armwrestling", "softball", "bodybuilding", "calisthenics", "dancing", "hockey", "frisbee", "kickboxing", "ski jumping", "horse riding", "roller skate", "billiard ball", "carrom", "bowling", "pool"],
        "Technology": ["computer", "ethernet cable", "integrated graphics", "cpu", "gpu", "internet", "wifi", "wireless", "bluetooth", "volume mixer", "cloud data", "iphone", "android", "samsung", "oneplus", "motherboard", "ram", "hard drive", "solid state drive", "power supplies", "amd", "intel", "nvdia", "gforce", "disk space", "data", "megabyte", "terabyte", "gigabyte", "upload", "download", "load", "save", "password", "username", "internet explorer", "microsoft paint", "apple", "google chrome", "microsoft edge", "firefox", "world wide web", "virus", "malware", "software", "installation", "hacker", "rom", "video game", "personal computer", "laptop"],
        "Pokemon": ["mewtwo", "arcanine", "gengar", "gyarados", "blastoise", "dragonite", "mew", "charizard", "articuno", "squirtle", "alakazam", "charmander", "zapdos", "scyther", "lapras", "venusaur", "snorlax", "bulbasaur", "ninetales", "dragonair", "growlithe", "charmeleon", "jolteon", "haunter", "vaporeon", "eevee", "aerodactyl", "moltres", "raichu", "pikachu", "ivysaur", "rapidash", "dratini", "pidgeot", "kabutops", "flareon", "cubone", "vulpix", "wartortle", "marowak", "onix", "golem", "kadabra", "hitmonlee", "electabuzz", "ditto", "poliwrath", "hitmonchan", "nidoqueen", "starmie", "sandslash", "magmar", "gastly", "abra", "cloyster", "tauros", "butterfree", "slowbro", "seadra", "kingler", "muk", "parasect", "kangaskhan", "pidgeotto", "dewgong", "pinsir", "arbok", "psyduck", "tentacruel", "ponyta", "chansey", "porygon", "poliwhirl", "beedrill", "magneton", "exeggutor", "magikarp", "persian", "poliwag", "machop", "jigglypuff", "omastar", "staryu", "hypno", "lickitung", "meowth", "dugtrio", "geodude", "nidorina", "horsea", "oddish", "weezing", "kabuto", "slowpoke", "dodrio", "pidgey", "krabby", "graveler", "caterpie", "venomoth", "clefairy", "clefable", "wigglytuff", "seel", "tangela", "diglett", "electrode", "shellder", "ekans", "magnemite", "grimer", "fearow", "koffing", "seaking", "drowzee"]
    }

    return categories[topic]
}

const getEmojiFromTopic = (topic) => {
    const topics = {
        "Nature":'🐞', 
        "Anime":'🍥',
        "Entertainment":'🍿',
        "Games":'🎮',
        "Food":'🌭',
        "General":'📕',
        "Music":'🎵',
        "Sports":'🏀',
        "Technology":'💻',
        "Pokemon":'🐲'
    }

    return topics[topic]
}

exports.getTopics = getTopics
exports.getWordsFromTopic = getWordsFromTopic
exports.getEmojiFromTopic = getEmojiFromTopic